### ISSUE TITLE
Data snapshot

### ISSUE THREAD

**Issue by stared** [oracleofnj/gitrank#6]
First, thanks for the project, and for sharing code!

Is it possible for you to attach downloaded `cached_repos.json.gz` and `cached_users.json.gz` files? It took me 2 nights of fetching and it is nowhere near there (~2100 crawled repos and users). I guess that also other could benefit from easily-accessible data.

**Comment by oracleofnj** [comment]
I would rather not add them to the repo since they are very large but I can email you a dropbox link. It looks like you are working on similar research so it would be fun to compare notes on how you have approached this clustering problem on other datasets.

**Comment by oracleofnj** [comment]
As a side note, my python code is pretty inefficient - at the beginning of the crawl, most of the time is spent waiting for GitHub's API but as those dictionaries get larger, it is wasting a lot of time sorting and rearranging them in memory since I was lazy in the implementation. It took a little over 24 hours for me to download all of the data here, with a big speed improvement coming from just stopping and restarting the download process halfway through. I do plan to fix this code to be less wasteful since I would like to set this up to do a scheduled crawl on a ~monthly basis.

**Comment by stared** [comment]
Sure, large binary files are not a good for git. But a Dropbox link would be nice.

Yes, I would like to play with it. In general, I am interested in various things related to clustering, decomposition (and D3.js visualization)!  For this thing I was thinking about making (either of users or repos similarity) using pointwise mutual information (see e.g. [TagOverflow](http://p.migdal.pl/tagoverflow/)) or to play with its decomposition (so-called skip-gram word2vec).

For clustering this kind of data (when you can look at edges as probabilities) I really recommend [Infomap](http://mapequation.org/code.html) (there are tons of community detection methods; but this one has nice foundation plus you get hierarchy for free).
